services:
    postgres:
        container_name: postgres
        image: postgres:latest
        environment:
            - POSTGRES_USER=prisma
            - POSTGRES_PASSWORD=prisma
            - POSTGRES_DB=prisma
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - '5444:5432'
volumes:
    db_data: